// AUTO-GENERATED by soltest-gen — Trident invariant scaffold.
// See solana-testing skill: trident-fuzzing.md + invariant-testing.md
// Encode the money invariants as plain assert!s; run `trident fuzz run`.
//
// Value-moving instructions detected: deposit, withdraw
//
// In your #[init], snapshot the total:
//   let initial = sum_all_token_and_lamport_balances();
// After every #[flow] and in #[end]:
//   assert!(sum_all_token_and_lamport_balances() == initial, "conservation violated");
//   assert!(total_mint_supply() == prev_supply || authorized_mint, "unauthorized mint");
//   assert!(only_authority_mutated_config(), "access-control bypass");
//
// Bind every numeric instruction arg via self.trident.random_from_range(..) so the
// fuzzer drives these flows into boundary values.
