#!/usr/bin/env node
// qa-gate — the release gate for full-stack web3 QA automation. Ingests a results
// manifest covering every QA layer (unit, integration, e2e, contract, formal, load,
// lighthouse, a11y, security-scan, uptime) and computes a single BLOCK/PASS verdict,
// plus a publishable QA report. Zero dependencies (Node >= 18). Library + CLI.
//
//   node qa-gate.mjs <manifest.json> [--report report.md]
//
// Manifest shape:
//   { "release": "v1.2.0", "layers": [
//     { "name": "unit",       "status": "pass", "required": true },
//     { "name": "e2e",        "status": "pass", "required": true },
//     { "name": "coverage",   "status": "pass", "metric": 0.86, "threshold": 0.80, "direction": "min", "required": true },
//     { "name": "lighthouse", "status": "pass", "metric": 0.93, "threshold": 0.90, "direction": "min", "required": true },
//     { "name": "load-p95ms", "status": "pass", "metric": 420,  "threshold": 500,  "direction": "max", "required": true },
//     { "name": "security",   "status": "pass", "required": true, "detail": "gitleaks + slither clean" },
//     { "name": "uptime",     "status": "pass", "metric": 99.95, "threshold": 99.9, "direction": "min", "required": false }
//   ] }
//
// A layer FAILS the gate when it is `required` and either status === "fail", or a metric
// breaches its threshold (min: metric < threshold; max: metric > threshold). `required:false`
// layers are reported but never block. status "skip" on a required layer is treated as a
// gap (blocks) unless `allowSkip:true` — you cannot ship what you didn't test.

export function evaluateLayer(layer) {
  const { status, metric, threshold, direction = "min", required = true, allowSkip = false } = layer;
  let ok = true;
  const notes = [];
  if (status === "fail") { ok = false; notes.push("status=fail"); }
  if (status === "skip" && !allowSkip) { ok = false; notes.push("required layer was skipped (untested)"); }
  if (typeof metric === "number" && typeof threshold === "number") {
    const breach = direction === "max" ? metric > threshold : metric < threshold;
    if (breach) { ok = false; notes.push(`${direction} threshold breached: ${metric} vs ${threshold}`); }
  }
  const blocks = required && !ok;
  return { name: layer.name, ok, required, blocks, status, metric, threshold, direction, notes, detail: layer.detail };
}

export function qaGate(manifest) {
  const results = (manifest.layers || []).map(evaluateLayer);
  const blockers = results.filter((r) => r.blocks);
  const warnings = results.filter((r) => !r.ok && !r.blocks);
  return { release: manifest.release || "(unversioned)", pass: blockers.length === 0, results, blockers, warnings };
}

export function toReport(gate) {
  const icon = (r) => (r.ok ? "✅" : r.blocks ? "🔴" : "⚠️");
  const lines = [];
  lines.push(`# QA Release Gate — ${gate.release}`);
  lines.push("");
  lines.push(gate.pass ? "## Verdict: 🟢 RELEASE ALLOWED" : "## Verdict: 🔴 RELEASE BLOCKED");
  lines.push("");
  lines.push("| Layer | Status | Metric | Required | Notes |");
  lines.push("|-------|--------|--------|----------|-------|");
  for (const r of gate.results) {
    const m = typeof r.metric === "number" ? `${r.metric}${r.threshold !== undefined ? ` (${r.direction} ${r.threshold})` : ""}` : "—";
    lines.push(`| ${icon(r)} ${r.name} | ${r.status || "—"} | ${m} | ${r.required ? "yes" : "no"} | ${r.notes.join("; ") || (r.detail || "")} |`);
  }
  if (gate.blockers.length) {
    lines.push("");
    lines.push("### Blockers");
    for (const b of gate.blockers) lines.push(`- 🔴 **${b.name}** — ${b.notes.join("; ")}`);
  }
  lines.push("");
  lines.push("_Generated by qa-gate. A gate that doesn't block on a real regression is decoration._");
  return lines.join("\n");
}

if (process.argv[1]?.endsWith("qa-gate.mjs")) {
  const { readFileSync, writeFileSync } = await import("node:fs");
  const args = process.argv.slice(2);
  const file = args.find((a) => !a.startsWith("-"));
  if (!file) { console.error("usage: node qa-gate.mjs <manifest.json> [--report report.md]"); process.exit(1); }
  const gate = qaGate(JSON.parse(readFileSync(file, "utf8")));
  console.log(`QA gate: ${gate.release} — ${gate.pass ? "PASS ✅" : "BLOCKED 🔴"}`);
  for (const b of gate.blockers) console.log(`  🔴 ${b.name}: ${b.notes.join("; ")}`);
  for (const w of gate.warnings) console.log(`  ⚠️  ${w.name} (non-blocking): ${w.notes.join("; ")}`);
  const rIdx = args.indexOf("--report");
  if (rIdx >= 0) { writeFileSync(args[rIdx + 1], toReport(gate)); console.log(`  report → ${args[rIdx + 1]}`); }
  process.exit(gate.pass ? 0 : 1);
}
