// AUTO-GENERATED by soltest-gen — Trident invariant scaffold.
// See solana-testing skill: trident-fuzzing.md + invariant-testing.md
// Encode the money invariants as plain assert!s; run `trident fuzz run`.
//
// Value-moving instructions detected: initLendingMarket, updateLendingMarket, updateLendingMarketOwner, updateReserveConfig, redeemFees, withdrawProtocolFee, seedDepositOnInitReserve, socializeLoss, socializeLossV2, depositReserveLiquidity, redeemReserveCollateral, depositObligationCollateral, depositObligationCollateralV2, withdrawObligationCollateral, withdrawObligationCollateralV2, borrowObligationLiquidity, borrowObligationLiquidityV2, repayObligationLiquidity, repayObligationLiquidityV2, repayAndWithdrawAndRedeem, depositAndWithdraw, depositReserveLiquidityAndObligationCollateral, depositReserveLiquidityAndObligationCollateralV2, withdrawObligationCollateralAndRedeemReserveCollateral, withdrawObligationCollateralAndRedeemReserveCollateralV2, liquidateObligationAndRedeemReserveCollateral, liquidateObligationAndRedeemReserveCollateralV2, flashRepayReserveLiquidity, flashBorrowReserveLiquidity, withdrawReferrerFees, setBorrowOrder, fillBorrowOrder, updateGlobalConfig, idlMissingTypes
//
// In your #[init], snapshot the total:
//   let initial = sum_all_token_and_lamport_balances();
// After every #[flow] and in #[end]:
//   assert!(sum_all_token_and_lamport_balances() == initial, "conservation violated");
//   assert!(total_mint_supply() == prev_supply || authorized_mint, "unauthorized mint");
//   assert!(only_authority_mutated_config(), "access-control bypass");
//
// Bind every numeric instruction arg via self.trident.random_from_range(..) so the
// fuzzer drives these flows into boundary values.
