#!/usr/bin/env node
// soltest-gen — turn an Anchor IDL into a complete adversarial test suite + a
// Mainnet-Readiness report. Zero dependencies (Node >= 18 builtins only).
//
//   node soltest-gen.mjs <program.idl.json> [--out DIR]
//
// It derives, per instruction, the fund-draining checks that apply (missing-signer,
// wrong-owner / account-substitution, re-initialization, arithmetic overflow, and
// value-conservation invariants), emits LiteSVM/@solana/kit test scaffolds + a
// Trident fuzz invariant scaffold + a CI workflow, and writes READINESS.md: a
// per-instruction × bug-class coverage matrix with a gate verdict.
//
// The generated tests are scaffolds (you fill program-load + fixtures, then run);
// the *generator itself* is exercised in tests/ and on examples/sample-escrow.idl.json.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, basename } from "node:path";

const INT_TYPES = new Set([
  "u8", "u16", "u32", "u64", "u128", "u256",
  "i8", "i16", "i32", "i64", "i128", "i256",
]);

const VALUE_VERB = /(withdraw|transfer|deposit|swap|mint|burn|claim|send|pay|settle|redeem|stake|unstake|lend|borrow|repay)/i;
const INIT_VERB = /(init|initialize|create|open|register|new)/i;
const AMOUNT_NAME = /(amount|lamports|qty|quantity|shares|tokens|value)/i;

// ── IDL normalization ──────────────────────────────────────────────────────
// Handles both the modern Anchor (>=0.30/1.x) IDL shape (account.writable /
// account.signer, top-level metadata.name) and the legacy (<=0.29) shape
// (account.isMut / account.isSigner, top-level `name`). Flattens nested
// composite account groups.
function normalizeIdl(idl) {
  const programName =
    idl?.metadata?.name ?? idl?.name ?? "program";

  const flattenAccounts = (accs, out = []) => {
    for (const a of accs ?? []) {
      if (Array.isArray(a.accounts)) {
        flattenAccounts(a.accounts, out); // composite group
      } else {
        out.push({
          name: a.name,
          writable: a.writable ?? a.isMut ?? false,
          signer: a.signer ?? a.isSigner ?? false,
        });
      }
    }
    return out;
  };

  const typeName = (t) => {
    if (typeof t === "string") return t;
    if (t && typeof t === "object") {
      if (t.defined) return "defined";
      if (t.option) return typeName(t.option);
      if (t.vec) return "vec";
      if (t.array) return "array";
    }
    return "unknown";
  };

  const instructions = (idl?.instructions ?? []).map((ix) => ({
    name: ix.name,
    accounts: flattenAccounts(ix.accounts),
    args: (ix.args ?? []).map((a) => ({ name: a.name, type: typeName(a.type) })),
  }));

  return { programName, instructions };
}

// ── Per-instruction risk analysis ───────────────────────────────────────────
function analyze(ix) {
  const signers = ix.accounts.filter((a) => a.signer).map((a) => a.name);
  // data accounts an attacker could substitute: writable and not a signer
  const substitutable = ix.accounts
    .filter((a) => a.writable && !a.signer)
    .map((a) => a.name);
  const intArgs = ix.args.filter((a) => INT_TYPES.has(a.type)).map((a) => a.name);
  const isInit = INIT_VERB.test(ix.name);
  const movesValue =
    VALUE_VERB.test(ix.name) || ix.args.some((a) => AMOUNT_NAME.test(a.name));

  const checks = {
    signer: signers,                 // missing-signer test per signer
    owner: substitutable,            // account-substitution test per writable data acct
    reinit: isInit,                  // re-initialization test
    overflow: intArgs,               // boundary test per integer arg
    conservation: movesValue,        // Trident money invariant
  };

  // severity: signer/owner/reinit on a value-moving ix are the drain classes
  const high =
    (movesValue && (signers.length || substitutable.length)) || (isInit && movesValue);

  return { ...checks, movesValue, isInit, high };
}

// ── Code generation ──────────────────────────────────────────────────────────
function genTsTest(ix, a, programName) {
  const L = [];
  L.push(`// AUTO-GENERATED by soltest-gen — adversarial scaffold for \`${ix.name}\`.`);
  L.push(`// Fill the TODO fixtures (program load + account data), then run.`);
  L.push(`// Layer: LiteSVM integration. See solana-testing skill: litesvm-integration.md`);
  L.push(`import { LiteSVM } from "litesvm";`);
  L.push(`import { Keypair } from "@solana/kit";`);
  L.push(``);
  L.push(`const PROGRAM = "${programName}";`);
  L.push(``);
  L.push(`describe("${ix.name}", () => {`);
  L.push(`  // TODO: const svm = new LiteSVM(); svm.addProgramFromFile(programId, "target/deploy/${programName}.so");`);
  L.push(``);
  L.push(`  it("succeeds on the happy path", () => {`);
  L.push(`    // TODO: build ${ix.name} with valid signers + accounts; assert success.`);
  L.push(`  });`);
  for (const s of a.signer) {
    L.push(``);
    L.push(`  // NEGATIVE — missing-signer: the drain class. Pass \`${s}\` as a non-signer.`);
    L.push(`  it("rejects when \`${s}\` does not sign", () => {`);
    L.push(`    // build ix with ${s}.isSigner = false; expect the tx to FAIL.`);
    L.push(`    // assert on FailedTransactionMetadata (MissingRequiredSignature / custom).`);
    L.push(`  });`);
  }
  for (const o of a.owner) {
    L.push(``);
    L.push(`  // NEGATIVE — account substitution: \`${o}\` owned by the wrong program.`);
    L.push(`  it("rejects a substituted \`${o}\` (wrong owner)", () => {`);
    L.push(`    // create a look-alike account with owner = a different program id; expect FAIL.`);
    L.push(`  });`);
  }
  if (a.reinit) {
    L.push(``);
    L.push(`  // NEGATIVE — re-initialization (init_if_needed / Nirvana-style).`);
    L.push(`  it("rejects or is idempotent on a second ${ix.name}", () => {`);
    L.push(`    // run ${ix.name}; mutate/fund; run ${ix.name} again.`);
    L.push(`    // assert 2nd FAILS (AlreadyInitialized) or state is unchanged (not reset).`);
    L.push(`  });`);
  }
  for (const n of a.overflow) {
    L.push(``);
    L.push(`  // NEGATIVE — arithmetic boundary on \`${n}\` (release builds wrap, not panic).`);
    L.push(`  it("handles \`${n}\` at u*::MAX / 0 without wrapping", () => {`);
    L.push(`    // call with ${n} = MAX and ${n} = balance+1; assert reject (checked_* path).`);
    L.push(`  });`);
  }
  L.push(`});`);
  L.push(``);
  return L.join("\n");
}

function genTridentInvariants(programName, valueIxs) {
  return `// AUTO-GENERATED by soltest-gen — Trident invariant scaffold.
// See solana-testing skill: trident-fuzzing.md + invariant-testing.md
// Encode the money invariants as plain assert!s; run \`trident fuzz run\`.
//
// Value-moving instructions detected: ${valueIxs.join(", ") || "(none)"}
//
// In your #[init], snapshot the total:
//   let initial = sum_all_token_and_lamport_balances();
// After every #[flow] and in #[end]:
//   assert!(sum_all_token_and_lamport_balances() == initial, "conservation violated");
//   assert!(total_mint_supply() == prev_supply || authorized_mint, "unauthorized mint");
//   assert!(only_authority_mutated_config(), "access-control bypass");
//
// Bind every numeric instruction arg via self.trident.random_from_range(..) so the
// fuzzer drives ${valueIxs.length ? "these flows" : "your flows"} into boundary values.
`;
}

function genCi(programName) {
  return `name: solana-tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.cache/solana
          key: \${{ runner.os }}-sbf-\${{ hashFiles('**/Cargo.lock') }}
      - name: Install Solana toolchain
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      - name: Unit + integration (SBF)
        run: cargo test-sbf
      # - name: Fuzz smoke
      #   run: cargo install trident-cli && trident fuzz run <target> # short, gated
      # - name: Readiness gate
      #   run: node tools/soltest-gen/soltest-gen.mjs target/idl/${programName}.json && cat READINESS.md
`;
}

function genReadiness(programName, analyzed) {
  const cls = ["signer", "owner", "reinit", "overflow", "conservation"];
  const label = {
    signer: "Missing-signer",
    owner: "Acct-substitution",
    reinit: "Re-init",
    overflow: "Overflow",
    conservation: "Conservation",
  };
  const applies = (a, c) => {
    if (c === "signer") return a.signer.length > 0;
    if (c === "owner") return a.owner.length > 0;
    if (c === "reinit") return a.reinit;
    if (c === "overflow") return a.overflow.length > 0;
    if (c === "conservation") return a.conservation;
  };

  let negTests = 0;   // discrete negative unit/integration tests
  let invariants = 0; // fuzz money invariants
  let highCount = 0;
  const rows = analyzed.map(({ ix, a }) => {
    const cells = cls.map((c) => {
      if (!applies(a, c)) return "—";
      const n =
        c === "signer" ? a.signer.length :
        c === "owner" ? a.owner.length :
        c === "overflow" ? a.overflow.length : 1;
      if (c === "conservation") invariants += n;
      else negTests += n;
      return `✅ ${n}`;
    });
    if (a.high) highCount++;
    return `| \`${ix.name}\`${a.high ? " ⚠️" : ""} | ${cells.join(" | ")} |`;
  });

  const ixCount = analyzed.length;
  const surface = analyzed.reduce(
    (s, { a }) => s + cls.filter((c) => applies(a, c)).length, 0
  );
  // Scaffold coverage = applicable checks that we generated tests for (always all).
  const scaffold = surface === 0 ? 100 : 100;

  return `# Mainnet-Readiness Report — \`${programName}\`

_Generated by soltest-gen. This grades your program's **adversarial test surface**, not a vibe._

## Verdict

- **Instructions analyzed:** ${ixCount}
- **Adversarial checks scaffolded:** ${negTests} negative tests + ${invariants} fuzz invariants = **${negTests + invariants}**
- **High-severity instructions** (value-moving with signer/owner/init risk): **${highCount}** ⚠️
- **Surface coverage:** ${scaffold}% of applicable bug-class checks scaffolded
- **Mainnet gate:** 🔴 **PENDING** — scaffolding ≠ passing. The gate goes 🟢 only when:
  1. every generated test passes (\`cargo test-sbf\`),
  2. fuzz invariants hold (\`trident fuzz run\`), and
  3. branch coverage confirms each guard line is reached (\`/check-coverage\`).

## Coverage matrix

| Instruction | Missing-signer | Acct-substitution | Re-init | Overflow | Conservation |
|---|---|---|---|---|---|
${rows.join("\n")}

✅ = tests generated (count). — = not applicable to this instruction. ⚠️ = high-severity.

## Next steps

1. Fill the fixtures in \`tests/generated/*.test.ts\` and run them.
2. Wire \`trident/${programName}_invariants.rs\` into your Trident target.
3. Add \`.github/workflows/solana-tests.yml\` (generated) so the gate runs on every PR.
4. Re-run \`/check-coverage\`; treat any uncovered guard branch as untested.

_See the solana-testing skill: bug-class-playbook.md, testing-pyramid.md._
`;
}

// ── Main ──────────────────────────────────────────────────────────────────────
function main(argv) {
  const args = argv.slice(2);
  if (args.length === 0 || args.includes("-h") || args.includes("--help")) {
    console.log("Usage: node soltest-gen.mjs <program.idl.json> [--out DIR]");
    process.exit(args.length === 0 ? 1 : 0);
  }
  const idlPath = args.find((a) => !a.startsWith("-"));
  const outIdx = args.indexOf("--out");
  const outDir = outIdx >= 0 ? args[outIdx + 1] : "./soltest-out";

  let idl;
  try {
    idl = JSON.parse(readFileSync(idlPath, "utf8"));
  } catch (e) {
    console.error(`error: cannot read/parse IDL at ${idlPath}: ${e.message}`);
    process.exit(1);
  }

  const { programName, instructions } = normalizeIdl(idl);
  if (instructions.length === 0) {
    console.error("error: no instructions found in IDL");
    process.exit(1);
  }

  const analyzed = instructions.map((ix) => ({ ix, a: analyze(ix) }));
  const valueIxs = analyzed.filter(({ a }) => a.movesValue).map(({ ix }) => ix.name);

  const write = (rel, content) => {
    const p = join(outDir, rel);
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    return p;
  };

  const written = [];
  for (const { ix, a } of analyzed) {
    written.push(write(`tests/generated/${ix.name}.test.ts`, genTsTest(ix, a, programName)));
  }
  written.push(write(`trident/${programName}_invariants.rs`, genTridentInvariants(programName, valueIxs)));
  written.push(write(`.github/workflows/solana-tests.yml`, genCi(programName)));
  written.push(write(`READINESS.md`, genReadiness(programName, analyzed)));

  const negTests = analyzed.reduce(
    (s, { a }) => s + a.signer.length + a.owner.length + a.overflow.length + (a.reinit ? 1 : 0),
    0
  );
  const invariants = analyzed.filter(({ a }) => a.conservation).length;
  console.log(`soltest-gen: ${programName}`);
  console.log(`  instructions:        ${instructions.length}`);
  console.log(`  negative tests:      ${negTests}`);
  console.log(`  fuzz invariants:     ${invariants}`);
  console.log(`  value-moving ix:     ${valueIxs.length} (${valueIxs.join(", ") || "none"})`);
  console.log(`  high-severity ix:    ${analyzed.filter(({ a }) => a.high).length}`);
  console.log(`  output dir:          ${outDir}`);
  console.log(`  files written:       ${written.length}`);
  console.log(`\nNext: open ${join(outDir, "READINESS.md")}`);
}

main(process.argv);
